### ISSUE TITLE
Text for queue all

### ISSUE THREAD

**Issue by classBabacar** [adamschachne/inhouse_bot#12]
Currently, you can !queue all but there is no way a user can know with the current queue so a small message to let them know.

**Comment by adamschachne** [comment]
Can you elaborate on this? Right now the bot will post the current queue after `!queue all` and the user will be able to see themselves in all roles

**Comment by classBabacar** [comment]
![Bot Queue All](https://user-images.githubusercontent.com/21285730/193486470-8e7f4301-e358-488a-8306-c094de7eeb5d.PNG)
In here it should say that you can also !queue all, I believe @adamschachne 

Intuitively, it might make sense to be able to "!queue all", but I dont think a message hurts

**Comment by adamschachne** [comment]
I see the problem now. what if it was changed to  `!queue <role> or !queue all to join, or ...`?

**Comment by adamschachne** [comment]
`!queue <role> @<user> <duo_role>` is also not mentioned there

**Comment by classBabacar** [comment]
I feel like we can remove the duo role, since it kinds of defeats the purpose of the inhouse or it brings a lot of complications when we have tournament code and things. 

But yea `!queue <role> or !queue all to queue for all roles`, would work. Also can remove the part that says `All non-queue messages are deleted` no point in telling the user that I think.
