### ISSUE TITLE
Tournament API

### ISSUE THREAD

**Issue by adamschachne** [adamschachne/inhouse_bot#16]
Utilize the riot games tournament api to create a lobby for a match when one is ready. This will both simplify the process for players, and allow us to automate the scoring of a match.

A tournament code should be generated when the game is found and the bot should post it to the channel (or DM it to users, though this may violate policies). The code/match id should also be saved into the database.

A background task will query active games and check the match history API for a game result. When a game is completed, wins and losses can be determined automatically. This should remove the `!won` command. The `!admin won` command can remain, however it should make sure that the background task does not continue checking the status of the affected game.

**Comment by adamschachne** [comment]
https://developer.riotgames.com/docs/lol#riot-games-api_tournament-api

**Comment by adamschachne** [comment]
An API is required to handle webhooks when the games are finished

`Receive game results in the form of an automatic callback (HTTP POST) from League of Legends servers whenever a game created using tournament code has been completed.`

**Comment by adamschachne** [comment]
Supposedly, the end-of-game data can be retrieved using the tournament code, in case the webhook was missed: `Pull end of game data based on given tournament code in case the callback is never received.
Query pre-game lobby player activity events for a given tournament code.` 

An API service and a background polling service should be used to keep track of tournament game progress. Codes should be stored in the database for persistence.

**Comment by adamschachne** [comment]
https://developer.riotgames.com/policies/general Policy requires that access to all APIs will require https. I'm assuming that includes the webhook endpoint, so the API server that runs will need signed certs.

For development/instances that have the Tournaments feature disabled, I'll include support for not providing certs.

**Comment by classBabacar** [comment]
You also can divide up this task, doesnt have to be 1 big pr that could have N number of bugs, the slower we go with this piece the better it will be in the end

**Comment by adamschachne** [comment]
Added a base framework for the http server and an empty background task in #44

**Comment by adamschachne** [comment]
These features will be configurable via an env variable because they will require a production riot application
