### ISSUE TITLE
Display User Data For Scouting

### ISSUE THREAD

**Issue by classBabacar** [adamschachne/inhouse_bot#31]
Use a command (```!scout``` to display data about a user, where that data is relevant to the inhouses)

Scouting a player should give a user information on how to potentially beat another player, or get into their headspace to figure out what the enemy player likes to do.

**Comment by adamschachne** [comment]
It'll probably annoy someone to !scout them since it mentions them.

**Comment by classBabacar** [comment]
yea I dont think there is a better way, unless in future we give each player a unique id to reference them

**Comment by adamschachne** [comment]
Maybe add an ability to search by player name. Player.name LIKE %name% for example.
