### ISSUE TITLE
Set Elo Functionality

### ISSUE THREAD

**Issue by classBabacar** [adamschachne/inhouse_bot#7]
Given there are a lot of varying elos in the microsoft league server, it would be helpful to group players based on their elo to make a fair match.

Example:
Bronze4-125 | Bronze3 - 150 | Bronze 2 - 175  | Bronze1-190
Silver4- 225..
Gold4- 325
Plat4 - 375
as elo goes higher difference between player is a bit more close
....

Possible call

!setElo {Discord_Id} {Elo_Number} where Elo_Number must be an integer

**Comment by adamschachne** [comment]
This should be an admin only function. Also, it should change the trueskill_mu and trueskill_sigma values of the PlayerRating

**Comment by classBabacar** [comment]
Agree, will possibly have to crunch some numbers to figure out the best values to use without breaking the algorithm
