### ISSUE TITLE
When a match is generated OP.gg of everyone in the game

### ISSUE THREAD

**Issue by classBabacar** [adamschachne/inhouse_bot#8]
When a lobby has 10 members ready to start/or when a match is finalized generated prodraft links

BLUE SIDE - {opgg link for blue side}
RED SIDE - {opgg link for red side}

underneath the list of teams

**Comment by classBabacar** [comment]
I think with the ways games are played now you don't need pro-draft. op.gg seems more valuable

**Comment by adamschachne** [comment]
Dependent on #16
